services:
  mysql:
    image: mysql:8
    container_name: mysql_tp
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp
    ports:
      - "3306:3306"
    volumes:
      - ./tp.sql:/docker-entrypoint-initdb.d/tp.sql